In [65]:
import numpy as np
import pandas as pd
from tensorflow import keras

np.set_printoptions(precision=2, formatter={'float':'{:,.2f}'.format})

In [36]:
x1 = np.array([x for x in range(50)]).reshape(-1,1)
x2 = np.array([10 * x for x in range(1, 51)]).reshape(-1,1)
x3 = np.array([10 * x for x in reversed(range(50))]).reshape(-1,1)

f = (x1 * x3 / x2) ** .5

In [37]:
data = np.concatenate((x1, x2, x3, f), axis=1)
data

array([[0.00, 10.00, 490.00, 0.00],
       [1.00, 20.00, 480.00, 4.90],
       [2.00, 30.00, 470.00, 5.60],
       [3.00, 40.00, 460.00, 5.87],
       [4.00, 50.00, 450.00, 6.00],
       [5.00, 60.00, 440.00, 6.06],
       [6.00, 70.00, 430.00, 6.07],
       [7.00, 80.00, 420.00, 6.06],
       [8.00, 90.00, 410.00, 6.04],
       [9.00, 100.00, 400.00, 6.00],
       [10.00, 110.00, 390.00, 5.95],
       [11.00, 120.00, 380.00, 5.90],
       [12.00, 130.00, 370.00, 5.84],
       [13.00, 140.00, 360.00, 5.78],
       [14.00, 150.00, 350.00, 5.72],
       [15.00, 160.00, 340.00, 5.65],
       [16.00, 170.00, 330.00, 5.57],
       [17.00, 180.00, 320.00, 5.50],
       [18.00, 190.00, 310.00, 5.42],
       [19.00, 200.00, 300.00, 5.34],
       [20.00, 210.00, 290.00, 5.26],
       [21.00, 220.00, 280.00, 5.17],
       [22.00, 230.00, 270.00, 5.08],
       [23.00, 240.00, 260.00, 4.99],
       [24.00, 250.00, 250.00, 4.90],
       [25.00, 260.00, 240.00, 4.80],
       [26.00, 270.00, 230.00, 

In [61]:
data[[3,13,33,45,6],1] = np.NaN
data[[2,15,40,49],2] = np.NaN
data[[1,11,22,44],3] = np.NaN
#data[3,[2,12,22]] = np.nanmean(data[:,2])

In [67]:
pd.DataFrame(data).corr()

0         1         2         3
0  1.000000  1.000000 -1.000000 -0.741901
1  1.000000  1.000000 -1.000000 -0.709079
2 -1.000000 -1.000000  1.000000  0.709099
3 -0.741901 -0.709079  0.709099  1.000000

In [59]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import ShuffleSplit, train_test_split
from sklearn.impute import SimpleImputer

imp = SimpleImputer(strategy='constant', fill_value=0)
data = imp.fit_transform(data)

alg = MLPRegressor(max_iter=10000, hidden_layer_sizes=(3, 3, 3), random_state=222)

data_train, data_test = train_test_split(data, random_state=51)

alg.fit(data_train[:,:-1], data_train[:,-1])
alg.score(data_test[:,:-1], data_test[:,-1])

0.1471848225083655

In [60]:
alg.predict(np.array([[500,2000,100], [5, 2, 10]])), (500 * 100/2000) ** .5, (5 * 10/2) ** .5

(array([2.53, 4.30]), 5.0, 5.0)

In [196]:
np.concatenate((data_test, alg.predict(data_test[:,:-1]).reshape(-1,1)), axis=1)

array([[33.00, 0.00, 9.00, 104.36, 7.40],
       [14.00, 140.00, 18.50, 44.27, 55.68],
       [4.00, 40.00, 23.50, 12.65, 20.03],
       [12.00, 120.00, 19.50, 37.95, 48.61],
       [49.00, 490.00, 0.00, 154.95, 175.94],
       [0.00, 0.00, 1,000.00, 0.00, -29.28],
       [34.00, 340.00, 8.50, 107.52, 124.69],
       [15.00, 150.00, 0.00, 47.43, 53.92],
       [38.00, 380.00, 6.50, 120.17, 138.46],
       [31.00, 310.00, 10.00, 98.03, 114.36],
       [17.00, 170.00, 17.00, 53.76, 66.16],
       [46.00, 460.00, 2.50, 145.46, 166.00],
       [2.00, 20.00, 0.00, 6.32, 7.26]])

In [204]:
alg.predict(np.array([900, 9000, 0]).reshape(1,-1))

array([2,844.98])

In [206]:
(900 * 9000) ** .5

2846.0498941515416

In [104]:
imp = SimpleImputer()
imp(data)

NameError: name 'SimpleImputer' is not defined

In [1]:
from scipy import optimize
optimize.shgo(eggholder, bounds)

NameError: name 'eggholder' is not defined

In [2]:
import numpy as np
np.log(10)

2.302585092994046

In [3]:
np.exp(np.log(10))

10.000000000000002