In [2]:
import numpy as np
import pandas as pd
from tensorflow import keras

np.set_printoptions(precision=2, formatter={'float':'{:,.2f}'.format})

In [4]:
x1 = np.array([x for x in range(50)]).reshape(-1,1)
x2 = np.array([x for x in range(1, 11)] * 5).reshape(-1,1)
x3 = np.array([x for x in reversed(range(50))]).reshape(-1,1)

f = (x1 * x3 / x2) ** .5

In [117]:
x4 = (x1 * x3)
data = np.concatenate((x1, x2, x3, x4, f), axis=1)


In [61]:
data[[3,13,33,45,6],1] = np.NaN
data[[2,15,40,49],2] = np.NaN
data[[1,11,22,44],3] = np.NaN
#data[3,[2,12,22]] = np.nanmean(data[:,2])

In [96]:
pd.DataFrame(data).corr()

0         1         2         3         4
0  1.000000  0.199037 -1.000000  0.000000 -0.007326
1  0.199037  1.000000 -0.199037  0.000000 -0.630631
2 -1.000000 -0.199037  1.000000  0.000000  0.007326
3  0.000000  0.000000  0.000000  1.000000  0.615517
4 -0.007326 -0.630631  0.007326  0.615517  1.000000

In [134]:
data = np.concatenate((x2, f), axis=1)

In [135]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import ShuffleSplit, train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MaxAbsScaler
from sklearn.pipeline import make_pipeline

imp = SimpleImputer(strategy='constant', fill_value=0)
sc = MaxAbsScaler()
data = make_pipeline(imp, sc).fit_transform(data)


alg = MLPRegressor(max_iter=10000, hidden_layer_sizes=(8, 8, 8), learning_rate_init=0.001, random_state=222, batch_size=1)

data_train, data_test = train_test_split(data, random_state=51)

alg.fit(data_train[:,:-1], data_train[:,-1])
alg.score(data_test[:,:-1], data_test[:,-1])

-0.9714228906245694

In [90]:
alg.predict(np.array([[500,4,100,50000], [5, 2, 10, 50]])), (500 * 100/4) ** .5, (5 * 10/2) ** .5

(array([870.94, 2.73]), 111.80339887498948, 5.0)

In [136]:
np.concatenate((data_test, alg.predict(data_test[:,:-1]).reshape(-1,1)), axis=1)

array([[0.50, 0.25, 0.42],
       [0.90, 0.10, 0.24],
       [0.80, 0.14, 0.27],
       [0.60, 0.38, 0.34],
       [0.10, 0.00, 0.71],
       [0.80, 0.34, 0.27],
       [1.00, 0.32, 0.21],
       [0.20, 0.69, 0.64],
       [1.00, 0.31, 0.21],
       [0.30, 0.23, 0.56],
       [0.40, 0.51, 0.49],
       [1.00, 0.26, 0.21],
       [0.50, 0.28, 0.42]])

In [204]:
alg.predict(np.array([900, 9000, 0]).reshape(1,-1))

array([2,844.98])

In [206]:
(900 * 9000) ** .5

2846.0498941515416

In [104]:
imp = SimpleImputer()
imp(data)

NameError: name 'SimpleImputer' is not defined

In [1]:
from scipy import optimize
optimize.shgo(eggholder, bounds)

NameError: name 'eggholder' is not defined

In [2]:
import numpy as np
np.log(10)

2.302585092994046

In [3]:
np.exp(np.log(10))

10.000000000000002