In [1]:
import numpy as np
from tensorflow import keras

np.set_printoptions(precision=2, formatter={'float':'{:,.2f}'.format})

In [2]:
x1 = np.array([x for x in range(50)]).reshape(-1,1)
x2 = np.array([10 * x for x in range(50)]).reshape(-1,1)
x3 = np.array([0.5 * x for x in reversed(range(50))]).reshape(-1,1)

f = (x1 * x2) ** .5

In [3]:
data = np.concatenate((x1, x2, x3, f), axis=1)
data

array([[0.00, 0.00, 24.50, 0.00],
       [1.00, 10.00, 24.00, 3.16],
       [2.00, 20.00, 23.50, 6.32],
       [3.00, 30.00, 23.00, 9.49],
       [4.00, 40.00, 22.50, 12.65],
       [5.00, 50.00, 22.00, 15.81],
       [6.00, 60.00, 21.50, 18.97],
       [7.00, 70.00, 21.00, 22.14],
       [8.00, 80.00, 20.50, 25.30],
       [9.00, 90.00, 20.00, 28.46],
       [10.00, 100.00, 19.50, 31.62],
       [11.00, 110.00, 19.00, 34.79],
       [12.00, 120.00, 18.50, 37.95],
       [13.00, 130.00, 18.00, 41.11],
       [14.00, 140.00, 17.50, 44.27],
       [15.00, 150.00, 17.00, 47.43],
       [16.00, 160.00, 16.50, 50.60],
       [17.00, 170.00, 16.00, 53.76],
       [18.00, 180.00, 15.50, 56.92],
       [19.00, 190.00, 15.00, 60.08],
       [20.00, 200.00, 14.50, 63.25],
       [21.00, 210.00, 14.00, 66.41],
       [22.00, 220.00, 13.50, 69.57],
       [23.00, 230.00, 13.00, 72.73],
       [24.00, 240.00, 12.50, 75.89],
       [25.00, 250.00, 12.00, 79.06],
       [26.00, 260.00, 11.50, 82.22],

In [4]:
data[[3,13,33,45,6],1] = np.NaN
data[[2,15,40,49],2] = np.NaN
data[[1,11,22,44],3] = np.NaN
#data[3,[2,12,22]] = np.nanmean(data[:,2])

In [6]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import ShuffleSplit, train_test_split
from sklearn.impute import SimpleImputer

imp = SimpleImputer(strategy='constant', fill_value=0)
data = imp.fit_transform(data)

alg = MLPRegressor(max_iter=10000, hidden_layer_sizes=(60, 660), random_state=222)

data_train, data_test = train_test_split(data, random_state=51)

alg.fit(data_train[:,:-1], data_train[:,-1])
alg.score(data_test[:,:-1], data_test[:,-1])

0.423210766716244

In [8]:
alg.predict(np.array([[500,5000,0]]))

array([1,614.71])

In [196]:
np.concatenate((data_test, alg.predict(data_test[:,:-1]).reshape(-1,1)), axis=1)

array([[33.00, 0.00, 9.00, 104.36, 7.40],
       [14.00, 140.00, 18.50, 44.27, 55.68],
       [4.00, 40.00, 23.50, 12.65, 20.03],
       [12.00, 120.00, 19.50, 37.95, 48.61],
       [49.00, 490.00, 0.00, 154.95, 175.94],
       [0.00, 0.00, 1,000.00, 0.00, -29.28],
       [34.00, 340.00, 8.50, 107.52, 124.69],
       [15.00, 150.00, 0.00, 47.43, 53.92],
       [38.00, 380.00, 6.50, 120.17, 138.46],
       [31.00, 310.00, 10.00, 98.03, 114.36],
       [17.00, 170.00, 17.00, 53.76, 66.16],
       [46.00, 460.00, 2.50, 145.46, 166.00],
       [2.00, 20.00, 0.00, 6.32, 7.26]])

In [204]:
alg.predict(np.array([900, 9000, 0]).reshape(1,-1))

array([2,844.98])

In [206]:
(900 * 9000) ** .5

2846.0498941515416

In [104]:
imp = SimpleImputer()
imp(data)

NameError: name 'SimpleImputer' is not defined

In [1]:
from scipy import optimize
optimize.shgo(eggholder, bounds)

NameError: name 'eggholder' is not defined